### ISSUE TITLE
abaplint configuration

### ISSUE THREAD

**Issue by larshp** [openTCT/zotct_utils#20]
Hi,
Let me know I can help regarding the abaplint configuration?

currently it finds 1000+ issues, you can adjust the configuration file according to what suits you

more information about each rule at https://rules.abaplint.org

**Comment by egemenyilmaz** [comment]
Hi Lars,

I am aware of the issues and plan to reduce them both by editing the codebase and modifying some rules on the configuration file. 

But I feel like some rules may need a bit consideration since this repo is going to be a shell of our future product packages which are being planned to run on various (especially old version) client systems. 

Thank you very much for your contribution, it is a pleasure to know we could use your help on the abaplint configuration.

**Comment by larshp** [comment]
👍 just let me know, we can close the issue if you like?

**Comment by egemenyilmaz** [comment]
It's OK to remain open, I will take care of it soon.

**Comment by larshp** [comment]
with
`      "errorNamespace": "",`
abaplint will try to resolve everything, including SAP standard classes like `cl_abap_tabledescr`

set it to
`"errorNamespace": "^(Z|Y|LCL_|TY_|LIF_)",`
and abaplint will trust anything outside of the error namespace, ie trust that `cl_abap_tabledescr` exists

**Comment by egemenyilmaz** [comment]
@larshp I applied your recommendation and  that eliminated so many issues that I couldn't figured out in the first place, thanks. 👍

**Comment by egemenyilmaz** [comment]
As of now I have reduced the issues to 2.

These two issues are both pointing that "Method importing parameter "VALUE" does not exist" for these method calls below:

[https://github.com/openTCT/zotct_utils/blob/main/src/zotct_ubl/zotct_cl_ubl.clas.abap#L398](url)
[https://github.com/openTCT/zotct_utils/blob/main/src/zotct_ubl/zotct_cl_ubl.clas.abap#L427](url)

When I investigate these calls, I see that this method (IF_IXML_DOCUMENT->CREATE_SIMPLE_ELEMENT_NS) actually has an import parameter named "VALUE" so the error looks erronous to me.

@larshp maybe you could have a look at the issue if possible and confirm whether it's a glitch in the abaplint or it's really a problematic statement. Also I wonder if it's possible to ignore this particular error by editing the abaplint configuration file.

**Comment by larshp** [comment]
try again

In https://github.com/openTCT/zotct_utils/blob/main/abaplint.json#L16 the configuration uses https://github.com/abaplint/deps to verify some of the objects, I've added the VALUE parameter via https://github.com/abaplint/deps/pull/40

**Comment by larshp** [comment]
for each rule its possible to exclude some files, example: https://github.com/abapGit/abapGit/blob/main/abaplint.json#L166

but just submit issues if it looks like a false positive 😄

**Comment by egemenyilmaz** [comment]
Hi @larshp 

Thank you, but when I re-run the abaplint check, it still throws the same error, not sure if I am running the check properly so.

Edit: After merging a pull request the errors are gone.

**Comment by egemenyilmaz** [comment]
To summarize, after code revisions and abaplint configuration changes we have cleared all errors. 

Further contributions are going to be checked one by one from now on.

I am closing the issue for now, big thanks to @larshp for valuable help and contributions on the issue.
