### ISSUE TITLE
zotct_cl_itab_ext => min () / max (): only work with standard tables

### ISSUE THREAD

**Issue by victorizbitskiy** [openTCT/zotct_utils#40]
Hi!

Class **zotct_cl_itab_ext** methods *min()* and *max()* only work with STANDATD tables. 
What about SORTED and HASHED tables?

**Comment by egemenyilmaz** [comment]
Hi @victorizbitskiy ,

I think I ignored non-standard tables since my needs are just satisfied with standard tables. Now I see that your pull request works very well and merged it. Thank you very much for this valuable contribution. 

#41
